#!/usr/bin/env sh

if [ ! -f /etc/synoinfo.conf ];
then
  rand=$(cat /proc/sys/kernel/random/uuid | awk -F '-' '{print $1}')
  echo "unique=\"synology_${rand}_720+\"" > /etc/synoinfo.conf
fi
rm /.dockerenv

# create user
if ! id -un $UID &> /dev/null; then
adduser -q --system --home $PWD --shell "/bin/sh" --no-create-home --uid $UID --gid $GID --disabled-password thunder
fi

chown -R "$(id -un $UID):$(id -gn $UID)" /tmp/go-build/pan-xunlei-com/
chown "$(id -un $UID):$(id -gn $UID)" /downloads
su - "$(id -un $UID)" -c "/tmp/go-build/pan-xunlei-com/xunlei_cgi"
# /tmp/go-build/pan-xunlei-com/xunlei_cgi
